/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kaakaa_hoe' at '16/06/22 20:58' with Gradle 2.14
 *
 * @author kaakaa_hoe, @date 16/06/22 20:58
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
